import type {PackageJson} from '@grogarden/gro/package_json.js';

export const package_json = {
	name: '@fuz.dev/fuz_mastodon',
	description: 'Mastodon components and helpers for Svelte, SvelteKit, and Fuz',
	version: '0.1.0',
	license: 'MIT',
	homepage: 'https://mastodon.fuz.dev/',
	repository: 'https://github.com/fuz-dev/fuz_mastodon',
	author: {name: 'Ryan Atkinson', email: 'mail@ryanatkn.com', url: 'https://www.ryanatkn.com/'},
	type: 'module',
	engines: {node: '>=20.7'},
	scripts: {
		start: 'gro dev',
		dev: 'gro dev',
		build: 'gro build',
		test: 'gro test',
		deploy: 'gro deploy',
	},
	files: ['dist'],
	devDependencies: {
		'@changesets/changelog-git': '^0.1.14',
		'@feltjs/eslint-config': '^0.4.1',
		'@fuz.dev/fuz': '^0.73.0',
		'@fuz.dev/fuz_contextmenu': '^0.4.1',
		'@fuz.dev/fuz_dialog': '^0.3.1',
		'@fuz.dev/fuz_library': '^0.11.1',
		'@fuz.dev/svelte_intersect': '^0.5.1',
		'@grogarden/gro': '^0.96.0',
		'@grogarden/util': '^0.15.2',
		'@sveltejs/adapter-static': '^2.0.3',
		'@sveltejs/kit': '^1.27.0',
		'@sveltejs/package': '^2.2.2',
		'@typescript-eslint/eslint-plugin': '^6.9.0',
		'@typescript-eslint/parser': '^6.9.0',
		'date-fns': '^2.30.0',
		eslint: '^8.52.0',
		'eslint-plugin-svelte': '^2.34.0',
		prettier: '^3.0.3',
		'prettier-plugin-svelte': '^3.0.3',
		svelte: '^4.2.2',
		'svelte-check': '^3.5.2',
		tslib: '^2.6.2',
		typescript: '^5.2.2',
		uvu: '^0.5.6',
	},
	eslintConfig: {root: true, extends: '@feltjs'},
	prettier: {
		plugins: ['prettier-plugin-svelte'],
		useTabs: true,
		printWidth: 100,
		singleQuote: true,
		bracketSpacing: false,
		overrides: [{files: 'package.json', options: {useTabs: false}}],
	},
	exports: {
		'./mastodon.js': {default: './dist/mastodon.js', types: './dist/mastodon.d.ts'},
		'./MastodonStatusItem.svelte': {
			svelte: './dist/MastodonStatusItem.svelte',
			types: './dist/MastodonStatusItem.svelte.d.ts',
		},
		'./MastodonStatusTree.svelte': {
			svelte: './dist/MastodonStatusTree.svelte',
			types: './dist/MastodonStatusTree.svelte.d.ts',
		},
		'./package.gen.js': {default: './dist/package.gen.js', types: './dist/package.gen.d.ts'},
		'./package.js': {default: './dist/package.js', types: './dist/package.d.ts'},
		'./storage.js': {default: './dist/storage.js', types: './dist/storage.d.ts'},
		'./Toot.svelte': {svelte: './dist/Toot.svelte', types: './dist/Toot.svelte.d.ts'},
		'./TootInput.svelte': {
			svelte: './dist/TootInput.svelte',
			types: './dist/TootInput.svelte.d.ts',
		},
		'./TootLoader.svelte': {
			svelte: './dist/TootLoader.svelte',
			types: './dist/TootLoader.svelte.d.ts',
		},
	},
} satisfies PackageJson;
