// generated by library.gen.ts !! do not edit directly or risk lost data

import type {LibraryJson} from '@fuzdev/fuz_util/library_json.js';

export const library_json: LibraryJson = {
	package_json: {
		name: '@fuzdev/fuz_mastodon',
		version: '0.36.0',
		description: 'Mastodon components and helpers for Svelte, SvelteKit, and Fuz',
		glyph: '🦣',
		logo: 'logo.svg',
		logo_alt: 'a friendly purple spider facing you',
		public: true,
		license: 'MIT',
		homepage: 'https://mastodon.fuz.dev/',
		repository: 'https://github.com/fuzdev/fuz_mastodon',
		author: {
			name: 'Ryan Atkinson',
			email: 'mail@ryanatkn.com',
			url: 'https://www.ryanatkn.com/',
		},
		bugs: 'https://github.com/fuzdev/fuz_mastodon/issues',
		funding: 'https://www.ryanatkn.com/funding',
		scripts: {
			start: 'gro dev',
			dev: 'gro dev',
			build: 'gro build',
			check: 'gro check',
			test: 'gro test',
			preview: 'vite preview',
			deploy: 'gro deploy',
		},
		type: 'module',
		engines: {
			node: '>=22.15',
		},
		peerDependencies: {
			'@fuzdev/fuz_util': '>=0.39.0',
			'@fuzdev/fuz_ui': '>=0.162.0',
			'@fuzdev/fuz_css': '>=0.39.0',
			'@sveltejs/kit': '^2',
			'date-fns': '^4',
			'esm-env': '^1',
			svelte: '^5',
		},
		devDependencies: {
			'@changesets/changelog-git': '^0.2.1',
			'@fuzdev/fuz_util': '^0.40.0',
			'@ryanatkn/eslint-config': '^0.9.0',
			'@fuzdev/fuz_ui': '^0.165.0',
			'@fuzdev/fuz_code': '^0.36.0',
			'@ryanatkn/gro': '^0.179.0',
			'@fuzdev/fuz_css': '^0.39.0',
			'@sveltejs/adapter-static': '^3.0.10',
			'@sveltejs/kit': '^2.49.0',
			'@sveltejs/package': '^2.5.6',
			'@sveltejs/vite-plugin-svelte': '^6.2.1',
			'date-fns': '^4.1.0',
			eslint: '^9.39.1',
			'eslint-plugin-svelte': '^3.13.0',
			'esm-env': '^1.2.2',
			prettier: '^3.6.2',
			'prettier-plugin-svelte': '^3.4.0',
			svelte: '^5.44.1',
			'svelte-check': '^4.3.4',
			tslib: '^2.8.1',
			typescript: '^5.9.3',
			'typescript-eslint': '^8.48.0',
			vitest: '^4.0.14',
		},
		prettier: {
			plugins: ['prettier-plugin-svelte'],
			useTabs: true,
			printWidth: 100,
			singleQuote: true,
			bracketSpacing: false,
			overrides: [
				{
					files: 'package.json',
					options: {
						useTabs: false,
					},
				},
			],
		},
		sideEffects: ['**/*.css'],
		files: ['dist', 'src/lib/**/*.ts', '!src/lib/**/*.test.*', '!dist/**/*.test.*'],
		exports: {
			'./package.json': './package.json',
			'./*.js': {
				types: './dist/*.d.ts',
				default: './dist/*.js',
			},
			'./*.ts': {
				types: './dist/*.d.ts',
				default: './dist/*.js',
			},
			'./*.svelte': {
				types: './dist/*.svelte.d.ts',
				svelte: './dist/*.svelte',
				default: './dist/*.svelte',
			},
		},
	},
	source_json: {
		name: '@fuzdev/fuz_mastodon',
		version: '0.36.0',
		modules: [
			{
				path: 'mastodon_cache.svelte.ts',
				declarations: [
					{
						name: 'MastodonCache',
						kind: 'class',
						source_line: 6,
						members: [
							{
								name: 'load_data',
								kind: 'variable',
								modifiers: ['readonly'],
								type_signature: '() => Promise<Array<[Url, FetchValueCacheItem]> | null>',
							},
							{
								name: 'data',
								kind: 'variable',
								doc_comment: "If `undefined`, it's still loading. `null` means no data.",
								type_signature: 'FetchValueCache | undefined | null',
							},
							{
								name: 'constructor',
								kind: 'constructor',
								type_signature:
									'(load_data: () => Promise<[Url, { key: string; url: string; params: any; value: any; etag: string | null; last_modified: string | null; }][] | null>, load_on_mount?: boolean): MastodonCache',
								parameters: [
									{
										name: 'load_data',
										type: '() => Promise<[Url, { key: string; url: string; params: any; value: any; etag: string | null; last_modified: string | null; }][] | null>',
										optional: false,
									},
									{
										name: 'load_on_mount',
										type: 'boolean',
										optional: false,
										default_value: 'true',
									},
								],
							},
							{
								name: 'load',
								kind: 'variable',
							},
						],
					},
					{
						name: 'mastodon_cache_context',
						kind: 'variable',
						source_line: 32,
						type_signature:
							'{ get: (error_message?: string | undefined) => MastodonCache; get_maybe: () => MastodonCache | undefined; set: (value: MastodonCache) => MastodonCache; }',
					},
				],
			},
			{
				path: 'mastodon.ts',
				declarations: [
					{
						name: 'to_mastodon_status_url',
						kind: 'function',
						source_line: 18,
						type_signature: '(host: string, id: string): string',
						return_type: 'string',
						parameters: [
							{
								name: 'host',
								type: 'string',
								optional: false,
							},
							{
								name: 'id',
								type: 'string',
								optional: false,
							},
						],
					},
					{
						name: 'to_mastodon_status_url_with_author',
						kind: 'function',
						source_line: 21,
						type_signature: '(host: string, id: string, author: string): string',
						return_type: 'string',
						parameters: [
							{
								name: 'host',
								type: 'string',
								optional: false,
							},
							{
								name: 'id',
								type: 'string',
								optional: false,
							},
							{
								name: 'author',
								type: 'string',
								optional: false,
							},
						],
					},
					{
						name: 'to_mastodon_status_url_with_users_author',
						kind: 'function',
						doc_comment: 'longhand for `to_mastodon_status_url_with_author`, apperas',
						source_line: 30,
						type_signature: '(host: string, id: string, author: string): string',
						return_type: 'string',
						parameters: [
							{
								name: 'host',
								type: 'string',
								optional: false,
							},
							{
								name: 'id',
								type: 'string',
								optional: false,
							},
							{
								name: 'author',
								type: 'string',
								optional: false,
							},
						],
					},
					{
						name: 'to_mastodon_api_status_url',
						kind: 'function',
						source_line: 36,
						type_signature: '(host: string, id: string): string',
						return_type: 'string',
						parameters: [
							{
								name: 'host',
								type: 'string',
								optional: false,
							},
							{
								name: 'id',
								type: 'string',
								optional: false,
							},
						],
					},
					{
						name: 'to_mastodon_api_status_context_url',
						kind: 'function',
						source_line: 39,
						type_signature: '(host: string, id: string): string',
						return_type: 'string',
						parameters: [
							{
								name: 'host',
								type: 'string',
								optional: false,
							},
							{
								name: 'id',
								type: 'string',
								optional: false,
							},
						],
					},
					{
						name: 'to_mastodon_api_favourites_url',
						kind: 'function',
						source_line: 42,
						type_signature: '(host: string, id: string): string',
						return_type: 'string',
						parameters: [
							{
								name: 'host',
								type: 'string',
								optional: false,
							},
							{
								name: 'id',
								type: 'string',
								optional: false,
							},
						],
					},
					{
						name: 'MastodonStatusUrl',
						kind: 'type',
						source_line: 46,
						type_signature: 'MastodonStatusUrl',
						properties: [
							{
								name: 'href',
								kind: 'variable',
								type_signature: 'string',
							},
							{
								name: 'host',
								kind: 'variable',
								type_signature: 'string',
							},
							{
								name: 'status_id',
								kind: 'variable',
								type_signature: 'string',
							},
							{
								name: 'author',
								kind: 'variable',
								type_signature: 'string',
							},
						],
					},
					{
						name: 'parse_mastodon_status_url',
						kind: 'function',
						doc_comment:
							'Parses a url to a post or API endpoint for a post, aka Mastodon status context.',
						source_line: 58,
						type_signature: '(url: string): MastodonStatusUrl | null',
						return_type: 'MastodonStatusUrl | null',
						return_description: 'the parsed host and id params, if any',
						parameters: [
							{
								name: 'url',
								type: 'string',
								optional: false,
							},
						],
					},
					{
						name: 'fetch_mastodon_status_context',
						kind: 'function',
						source_line: 72,
						type_signature:
							'(host: string, id: string, cache?: Map<string, { key: string; url: string; params: any; value: any; etag: string | null; last_modified: string | null; }> | null | undefined, log?: Logger | undefined, request?: RequestInit | undefined, token?: string | undefined, fetch?: ((input: RequestInfo | URL, init?: RequestInit | undefined) => Promise<...>) | undefined): Promise<...>',
						return_type: 'Promise<MastodonStatusContext | null>',
						parameters: [
							{
								name: 'host',
								type: 'string',
								optional: false,
							},
							{
								name: 'id',
								type: 'string',
								optional: false,
							},
							{
								name: 'cache',
								type: 'Map<string, { key: string; url: string; params: any; value: any; etag: string | null; last_modified: string | null; }> | null | undefined',
								optional: true,
							},
							{
								name: 'log',
								type: 'Logger | undefined',
								optional: true,
							},
							{
								name: 'request',
								type: 'RequestInit | undefined',
								optional: true,
							},
							{
								name: 'token',
								type: 'string | undefined',
								optional: true,
							},
							{
								name: 'fetch',
								type: '((input: RequestInfo | URL, init?: RequestInit | undefined) => Promise<Response>) | undefined',
								optional: true,
							},
						],
					},
					{
						name: 'fetch_mastodon_status',
						kind: 'function',
						source_line: 94,
						type_signature:
							'(host: string, id: string, cache?: Map<string, { key: string; url: string; params: any; value: any; etag: string | null; last_modified: string | null; }> | null | undefined, log?: Logger | undefined, request?: RequestInit | undefined, token?: string | undefined, fetch?: ((input: RequestInfo | URL, init?: RequestInit | undefined) => Promise<...>) | undefined): Promise<...>',
						return_type: 'Promise<MastodonStatus | null>',
						parameters: [
							{
								name: 'host',
								type: 'string',
								optional: false,
							},
							{
								name: 'id',
								type: 'string',
								optional: false,
							},
							{
								name: 'cache',
								type: 'Map<string, { key: string; url: string; params: any; value: any; etag: string | null; last_modified: string | null; }> | null | undefined',
								optional: true,
							},
							{
								name: 'log',
								type: 'Logger | undefined',
								optional: true,
							},
							{
								name: 'request',
								type: 'RequestInit | undefined',
								optional: true,
							},
							{
								name: 'token',
								type: 'string | undefined',
								optional: true,
							},
							{
								name: 'fetch',
								type: '((input: RequestInfo | URL, init?: RequestInit | undefined) => Promise<Response>) | undefined',
								optional: true,
							},
						],
					},
					{
						name: 'fetch_mastodon_favourites',
						kind: 'function',
						source_line: 116,
						type_signature:
							'(host: string, status_id: string, cache?: Map<string, { key: string; url: string; params: any; value: any; etag: string | null; last_modified: string | null; }> | null | undefined, log?: Logger | undefined, request?: RequestInit | undefined, token?: string | undefined, fetch?: ((input: RequestInfo | URL, init?: RequestInit | undefined) => Promise<...>) | undefined): Promise<...>',
						return_type: 'Promise<MastodonFavourite[] | null>',
						parameters: [
							{
								name: 'host',
								type: 'string',
								optional: false,
							},
							{
								name: 'status_id',
								type: 'string',
								optional: false,
							},
							{
								name: 'cache',
								type: 'Map<string, { key: string; url: string; params: any; value: any; etag: string | null; last_modified: string | null; }> | null | undefined',
								optional: true,
							},
							{
								name: 'log',
								type: 'Logger | undefined',
								optional: true,
							},
							{
								name: 'request',
								type: 'RequestInit | undefined',
								optional: true,
							},
							{
								name: 'token',
								type: 'string | undefined',
								optional: true,
							},
							{
								name: 'fetch',
								type: '((input: RequestInfo | URL, init?: RequestInit | undefined) => Promise<Response>) | undefined',
								optional: true,
							},
						],
					},
					{
						name: 'MastodonStatusContext',
						kind: 'type',
						doc_comment: 'Result from `https://:host/api/v1/statuses/:id/context`.',
						see_also: ['https://docs.joinmastodon.org/entities/Context/'],
						source_line: 144,
						type_signature: 'MastodonStatusContext',
						properties: [
							{
								name: 'ancestors',
								kind: 'variable',
								type_signature: 'Array<MastodonStatus>',
							},
							{
								name: 'descendants',
								kind: 'variable',
								type_signature: 'Array<MastodonStatus>',
							},
						],
					},
					{
						name: 'MastodonStatus',
						kind: 'type',
						source_line: 149,
						type_signature: 'MastodonStatus',
						properties: [
							{
								name: 'id',
								kind: 'variable',
								type_signature: 'string',
							},
							{
								name: 'created_at',
								kind: 'variable',
								type_signature: 'string',
							},
							{
								name: 'in_reply_to_id',
								kind: 'variable',
								type_signature: 'string',
							},
							{
								name: 'in_reply_to_account_id',
								kind: 'variable',
								type_signature: 'string',
							},
							{
								name: 'sensitive',
								kind: 'variable',
								type_signature: 'boolean',
							},
							{
								name: 'spoiler_text',
								kind: 'variable',
								type_signature: 'string',
							},
							{
								name: 'visibility',
								kind: 'variable',
								type_signature: 'string',
							},
							{
								name: 'language',
								kind: 'variable',
								type_signature: 'string',
							},
							{
								name: 'uri',
								kind: 'variable',
								type_signature: 'string',
							},
							{
								name: 'url',
								kind: 'variable',
								type_signature: 'string',
							},
							{
								name: 'replies_count',
								kind: 'variable',
								type_signature: 'number',
							},
							{
								name: 'reblogs_count',
								kind: 'variable',
								type_signature: 'number',
							},
							{
								name: 'favourites_count',
								kind: 'variable',
								type_signature: 'number',
							},
							{
								name: 'edited_at',
								kind: 'variable',
								type_signature: 'null | string',
							},
							{
								name: 'favourited',
								kind: 'variable',
								type_signature: 'boolean',
							},
							{
								name: 'reblogged',
								kind: 'variable',
								type_signature: 'boolean',
							},
							{
								name: 'muted',
								kind: 'variable',
								type_signature: 'boolean',
							},
							{
								name: 'bookmarked',
								kind: 'variable',
								type_signature: 'boolean',
							},
							{
								name: 'content',
								kind: 'variable',
								type_signature: 'string',
							},
							{
								name: 'filtered',
								kind: 'variable',
								type_signature: 'Array<unknown>',
							},
							{
								name: 'reblog',
								kind: 'variable',
								type_signature: 'unknown',
							},
							{
								name: 'account',
								kind: 'variable',
								type_signature:
									'{\n\t\tid: string;\n\t\tusername: string;\n\t\tacct: string;\n\t\tdisplay_name: string;\n\t\tlocked: boolean;\n\t\tbot: boolean;\n\t\tdiscoverable: boolean;\n\t\tgroup: boolean;\n\t\tcreated_at: string;\n\t\tnote: string;\n\t\turl: string;\n\t\tavatar: string;\n\t\tavatar_static: string;\n\t\theader: string;\n\t\theader_static: string;\n\t\tfollowers_count: number;\n\t\tfollowing_count: number;\n\t\tstatuses_count: number;\n\t\tlast_status_at: string;\n\t\temojis: Array<unknown>;\n\t\tfields: Array<unknown>;\n\t}',
							},
							{
								name: 'media_attachments',
								kind: 'variable',
								type_signature: 'Array<unknown>',
							},
							{
								name: 'mentions',
								kind: 'variable',
								type_signature:
									'[\n\t\t{\n\t\t\tid: string;\n\t\t\tusername: string;\n\t\t\turl: string;\n\t\t\tacct: string;\n\t\t},\n\t]',
							},
							{
								name: 'tags',
								kind: 'variable',
								type_signature: '[\n\t\t{\n\t\t\tname: string;\n\t\t\turl: string;\n\t\t},\n\t]',
							},
							{
								name: 'emojis',
								kind: 'variable',
								type_signature: 'Array<unknown>',
							},
							{
								name: 'card',
								kind: 'variable',
								type_signature: 'unknown',
							},
							{
								name: 'poll',
								kind: 'variable',
								type_signature: 'unknown',
							},
						],
					},
					{
						name: 'MastodonFavourite',
						kind: 'type',
						source_line: 214,
						type_signature: 'MastodonFavourite',
						properties: [
							{
								name: 'id',
								kind: 'variable',
								type_signature: 'string',
							},
							{
								name: 'username',
								kind: 'variable',
								type_signature: 'string',
							},
							{
								name: 'acct',
								kind: 'variable',
								type_signature: 'string',
							},
							{
								name: 'display_name',
								kind: 'variable',
								type_signature: 'string',
							},
							{
								name: 'locked',
								kind: 'variable',
								type_signature: 'boolean',
							},
							{
								name: 'bot',
								kind: 'variable',
								type_signature: 'boolean',
							},
							{
								name: 'discoverable',
								kind: 'variable',
								type_signature: 'boolean',
							},
							{
								name: 'group',
								kind: 'variable',
								type_signature: 'boolean',
							},
							{
								name: 'created_at',
								kind: 'variable',
								type_signature: 'string',
							},
							{
								name: 'note',
								kind: 'variable',
								type_signature: 'string',
							},
							{
								name: 'url',
								kind: 'variable',
								type_signature: 'string',
							},
							{
								name: 'avatar',
								kind: 'variable',
								type_signature: 'string',
							},
							{
								name: 'avatar_static',
								kind: 'variable',
								type_signature: 'string',
							},
							{
								name: 'header',
								kind: 'variable',
								type_signature: 'string',
							},
							{
								name: 'header_static',
								kind: 'variable',
								type_signature: 'string',
							},
							{
								name: 'followers_count',
								kind: 'variable',
								type_signature: 'number',
							},
							{
								name: 'following_count',
								kind: 'variable',
								type_signature: 'number',
							},
							{
								name: 'statuses_count',
								kind: 'variable',
								type_signature: 'number',
							},
							{
								name: 'last_status_at',
								kind: 'variable',
								type_signature: 'string',
							},
							{
								name: 'emojis',
								kind: 'variable',
								type_signature: 'Array<unknown>',
							},
							{
								name: 'fields',
								kind: 'variable',
								type_signature:
									'Array<{\n\t\tname: string;\n\t\tvalue: string;\n\t\tverified_at: string; // Datetime\n\t}>',
							},
						],
					},
					{
						name: 'ReplyFilter',
						kind: 'type',
						doc_comment:
							'When filtering replies, at least one rule must pass for a reply to be included.',
						source_line: 245,
						type_signature: 'ReplyFilter',
					},
					{
						name: 'FavouritedByReplyFilter',
						kind: 'type',
						source_line: 250,
						type_signature: 'FavouritedByReplyFilter',
						properties: [
							{
								name: 'type',
								kind: 'variable',
								type_signature: "'favourited_by'",
							},
							{
								name: 'favourited_by',
								kind: 'variable',
								type_signature: 'Array<string>',
							},
						],
					},
					{
						name: 'MinimumFavouritesReplyFilter',
						kind: 'type',
						source_line: 255,
						type_signature: 'MinimumFavouritesReplyFilter',
						properties: [
							{
								name: 'type',
								kind: 'variable',
								type_signature: "'minimum_favourites'",
							},
							{
								name: 'minimum_favourites',
								kind: 'variable',
								type_signature: 'number',
							},
						],
					},
					{
						name: 'CustomReplyFilter',
						kind: 'type',
						source_line: 260,
						type_signature: 'CustomReplyFilter',
						properties: [
							{
								name: 'type',
								kind: 'variable',
								type_signature: "'custom'",
							},
							{
								name: 'should_include',
								kind: 'variable',
								type_signature:
									'(\n\t\tstatus: MastodonStatus,\n\t\troot_status: MastodonStatus,\n\t\tstatus_context: MastodonStatusContext,\n\t) => boolean',
							},
						],
					},
					{
						name: 'CreateReplyFilters',
						kind: 'type',
						source_line: 269,
						type_signature: 'CreateReplyFilters',
					},
					{
						name: 'filter_valid_replies',
						kind: 'function',
						source_line: 276,
						type_signature:
							'(root_status: MastodonStatus, status_context: MastodonStatusContext, reply_filter: ReplyFilter | ReplyFilter[] | null, cache: Map<...> | ... 1 more ... | undefined, log: Logger | undefined): Promise<...>',
						return_type: 'Promise<MastodonStatus[]>',
						parameters: [
							{
								name: 'root_status',
								type: 'MastodonStatus',
								optional: false,
							},
							{
								name: 'status_context',
								type: 'MastodonStatusContext',
								optional: false,
							},
							{
								name: 'reply_filter',
								type: 'ReplyFilter | ReplyFilter[] | null',
								optional: false,
							},
							{
								name: 'cache',
								type: 'Map<string, { key: string; url: string; params: any; value: any; etag: string | null; last_modified: string | null; }> | null | undefined',
								optional: false,
							},
							{
								name: 'log',
								type: 'Logger | undefined',
								optional: false,
							},
						],
					},
				],
				dependents: ['Toot.svelte', 'TootInput.svelte', 'TootLoader.svelte'],
			},
			{
				path: 'MastodonStatusItem.svelte',
				declarations: [
					{
						name: 'MastodonStatusItem',
						kind: 'component',
						props: [
							{
								name: 'item',
								type: 'MastodonStatus',
								optional: false,
							},
						],
						source_line: 1,
					},
				],
				dependents: ['MastodonStatusTree.svelte', 'Toot.svelte'],
			},
			{
				path: 'MastodonStatusTree.svelte',
				declarations: [
					{
						name: 'MastodonStatusTree',
						kind: 'component',
						props: [
							{
								name: 'item',
								type: 'MastodonStatus',
								optional: false,
							},
							{
								name: 'items',
								type: 'Array<MastodonStatus>',
								optional: false,
							},
						],
						source_line: 1,
					},
				],
				dependencies: ['MastodonStatusItem.svelte', 'MastodonStatusTree.svelte'],
				dependents: ['MastodonStatusTree.svelte', 'Toot.svelte'],
			},
			{
				path: 'storage.ts',
				declarations: [
					{
						name: 'load_from_storage',
						kind: 'function',
						doc_comment:
							'Loads `key` and falls back to `defaultValue`.\nIf `validate` is provided and throws, it removes the `key` and returns `undefined`.',
						source_line: 13,
						type_signature:
							'<T>(key: string, to_default_value: () => T, validate?: ((value: any) => asserts value is T) | undefined): T',
						return_type: 'T',
						parameters: [
							{
								name: 'key',
								type: 'string',
								optional: false,
							},
							{
								name: 'to_default_value',
								type: '() => T',
								optional: false,
							},
							{
								name: 'validate',
								type: '((value: any) => asserts value is T) | undefined',
								optional: true,
							},
						],
					},
					{
						name: 'set_in_storage',
						kind: 'function',
						doc_comment:
							'Sets `value` at `key`.\nImportantly, if `value` is `undefined` the `key` is removed,\nbut a `value` of `null` is stored.',
						source_line: 40,
						type_signature: '(key: string, value: any): void',
						return_type: 'void',
						parameters: [
							{
								name: 'key',
								type: 'string',
								optional: false,
							},
							{
								name: 'value',
								type: 'any',
								optional: false,
							},
						],
					},
				],
				dependents: ['Toot.svelte'],
			},
			{
				path: 'Toot.svelte',
				declarations: [
					{
						name: 'Toot',
						kind: 'component',
						props: [
							{
								name: 'url',
								type: 'string',
								optional: false,
							},
							{
								name: 'updated_url',
								type: 'string',
								optional: true,
								description: 'Defaults to the `url`, but can be updated by user input.',
								bindable: true,
							},
							{
								name: 'include_ancestors',
								type: 'boolean',
								optional: true,
								description: 'Whether to fetch and display the ancestors in the status context.',
							},
							{
								name: 'include_replies',
								type: 'boolean',
								optional: true,
								description:
									'Whether to fetch and display replies aka descendants in the status context.',
							},
							{
								name: 'reply_filter',
								type: 'ReplyFilter | Array<ReplyFilter> | CreateReplyFilters | null',
								optional: true,
								description: 'Get a list of rules that controls whether replies are shown or not.',
							},
							{
								name: 'cache',
								type: 'FetchValueCache | null | undefined',
								optional: true,
								description:
									'Optional API result cache.\nSee `MastodonCache` and `get_mastodon_cache`/`set_mastodon_cache`.',
							},
							{
								name: 'log',
								type: 'Logger | undefined',
								optional: true,
								description: 'Optional logger for network calls.',
							},
							{
								name: 'loading',
								type: 'boolean | undefined',
								optional: true,
								description: '',
								bindable: true,
							},
							{
								name: 'load_time',
								type: 'number | undefined',
								optional: true,
								description: '',
								bindable: true,
							},
							{
								name: 'settings_storage_key',
								type: 'string | undefined',
								optional: true,
							},
							{
								name: 'initial_show_settings',
								type: 'boolean',
								optional: true,
							},
							{
								name: 'show_settings',
								type: 'boolean',
								optional: true,
								bindable: true,
							},
							{
								name: 'autoload_storage_key',
								type: 'string | undefined',
								optional: true,
							},
							{
								name: 'initial_autoload',
								type: 'boolean',
								optional: true,
							},
							{
								name: 'autoload',
								type: 'boolean',
								optional: true,
							},
							{
								name: 'onreset',
								type: '() => void',
								optional: true,
							},
							{
								name: 'settings',
								type: 'Snippet',
								optional: true,
							},
						],
						source_line: 1,
					},
				],
				dependencies: [
					'MastodonStatusItem.svelte',
					'MastodonStatusTree.svelte',
					'TootInput.svelte',
					'TootLoader.svelte',
					'mastodon.ts',
					'storage.ts',
				],
			},
			{
				path: 'TootInput.svelte',
				declarations: [
					{
						name: 'TootInput',
						kind: 'component',
						props: [
							{
								name: 'url',
								type: 'string',
								optional: false,
								bindable: true,
							},
							{
								name: 'attrs',
								type: "SvelteHTMLElements['input'] | undefined",
								optional: true,
							},
						],
						source_line: 1,
					},
				],
				dependencies: ['mastodon.ts'],
				dependents: ['Toot.svelte'],
			},
			{
				path: 'TootLoader.svelte',
				declarations: [
					{
						name: 'TootLoader',
						kind: 'component',
						props: [
							{
								name: 'host',
								type: 'string | null',
								optional: false,
								description: "The host part of the url, like `'mastodon.ryanatkn.com'`.",
							},
							{
								name: 'id',
								type: 'string | null',
								optional: false,
								description: "The status id to fetch, like `'110702983310017651'`.",
							},
							{
								name: 'include_ancestors',
								type: 'boolean',
								optional: true,
								description: 'Whether to fetch and display the ancestors in the status context.',
							},
							{
								name: 'include_replies',
								type: 'boolean',
								optional: true,
								description:
									'Whether to fetch and display replies aka descendants in the status context.',
							},
							{
								name: 'cache',
								type: 'FetchValueCache | null | undefined',
								optional: true,
								description: 'Optional API result cache.',
							},
							{
								name: 'log',
								type: 'Logger | undefined',
								optional: true,
								description: 'Optional logger for network calls.',
							},
							{
								name: 'loading',
								type: 'boolean | undefined',
								optional: true,
								bindable: true,
							},
							{
								name: 'item',
								type: 'MastodonStatus | null | undefined',
								optional: true,
								bindable: true,
							},
							{
								name: 'status_context',
								type: 'MastodonStatusContext | null | undefined',
								optional: true,
								bindable: true,
							},
							{
								name: 'replies',
								type: 'Array<MastodonStatus> | null | undefined',
								optional: true,
								bindable: true,
							},
							{
								name: 'reply_filter',
								type: 'ReplyFilter | Array<ReplyFilter> | CreateReplyFilters | null',
								optional: true,
								description:
									'Get a list of rules that controls whether replies are shown or not.\nIf omitted, all replies are included.',
							},
							{
								name: 'load_time',
								type: 'number | undefined',
								optional: true,
								bindable: true,
							},
							{
								name: 'children',
								type: 'Snippet<\n\t\t\t[\n\t\t\t\t{\n\t\t\t\t\t/**\n\t\t\t\t\t * `null` here is a failed loading condition.\n\t\t\t\t\t */\n\t\t\t\t\titem: MastodonStatus | null | undefined;\n\t\t\t\t\t/**\n\t\t\t\t\t * `null` here is a failed loading condition.\n\t\t\t\t\t */\n\t\t\t\t\tstatus_context: MastodonStatusContext | null | undefined;\n\t\t\t\t\t/**\n\t\t\t\t\t * `null` here is a failed loading condition for `item` or `status_context`.\n\t\t\t\t\t */\n\t\t\t\t\treplies: Array<MastodonStatus> | null | undefined;\n\t\t\t\t\tload: () => Promise<void>;\n\t\t\t\t\tloading: boolean | undefined;\n\t\t\t\t\tload_time: number | undefined;\n\t\t\t\t},\n\t\t\t]\n\t\t>',
								optional: false,
							},
						],
						source_line: 1,
					},
				],
				dependencies: ['mastodon.ts'],
				dependents: ['Toot.svelte'],
			},
		],
	},
	name: '@fuzdev/fuz_mastodon',
	repo_name: 'fuz_mastodon',
	repo_url: 'https://github.com/fuzdev/fuz_mastodon',
	owner_name: 'ryanatkn',
	homepage_url: 'https://mastodon.fuz.dev/',
	logo_url: 'https://mastodon.fuz.dev/logo.svg',
	logo_alt: 'a friendly purple spider facing you',
	npm_url: 'https://www.npmjs.com/package/@fuzdev/fuz_mastodon',
	changelog_url: 'https://github.com/fuzdev/fuz_mastodon/blob/main/CHANGELOG.md',
	published: true,
};

// generated by library.gen.ts !! do not edit directly or risk lost data
