// Generated by package.gen.ts
// Do not edit directly - regenerated on build

import type {Package_Json} from '@ryanatkn/belt/package_json.js';
import type {Src_Json} from '@ryanatkn/belt/src_json.js';

export const package_json: Package_Json = {
	name: '@ryanatkn/fuz_mastodon',
	version: '0.32.0',
	description: 'Mastodon components and helpers for Svelte, SvelteKit, and Fuz',
	glyph: '🦣',
	logo: 'logo.svg',
	logo_alt: 'a friendly purple spider facing you',
	public: true,
	license: 'MIT',
	homepage: 'https://mastodon.fuz.dev/',
	repository: 'https://github.com/ryanatkn/fuz_mastodon',
	author: {
		name: 'Ryan Atkinson',
		email: 'mail@ryanatkn.com',
		url: 'https://www.ryanatkn.com/',
	},
	bugs: 'https://github.com/ryanatkn/fuz_mastodon/issues',
	funding: 'https://www.ryanatkn.com/funding',
	scripts: {
		start: 'gro dev',
		dev: 'gro dev',
		build: 'gro build',
		check: 'gro check',
		test: 'gro test',
		preview: 'vite preview',
		deploy: 'gro deploy',
	},
	type: 'module',
	engines: {
		node: '>=22.15',
	},
	peerDependencies: {
		'@ryanatkn/belt': '>=0.35.1',
		'@ryanatkn/fuz': '>=0.147.0',
		'@ryanatkn/moss': '>=0.36.2',
		'@sveltejs/kit': '^2',
		'date-fns': '^4',
		'esm-env': '^1',
		svelte: '^5',
	},
	devDependencies: {
		'@changesets/changelog-git': '^0.2.1',
		'@ryanatkn/belt': '^0.38.0',
		'@ryanatkn/eslint-config': '^0.9.0',
		'@ryanatkn/fuz': '^0.158.0',
		'@ryanatkn/fuz_code': '^0.34.0',
		'@ryanatkn/gro': '^0.174.2',
		'@ryanatkn/moss': '^0.38.0',
		'@sveltejs/adapter-static': '^3.0.10',
		'@sveltejs/kit': '^2.49.0',
		'@sveltejs/package': '^2.5.6',
		'@sveltejs/vite-plugin-svelte': '^6.2.1',
		'date-fns': '^4.1.0',
		eslint: '^9.39.1',
		'eslint-plugin-svelte': '^3.13.0',
		'esm-env': '^1.2.2',
		prettier: '^3.6.2',
		'prettier-plugin-svelte': '^3.4.0',
		svelte: '^5.43.14',
		'svelte-check': '^4.3.4',
		tslib: '^2.8.1',
		typescript: '^5.9.3',
		'typescript-eslint': '^8.47.0',
		vitest: '^4.0.13',
	},
	prettier: {
		plugins: ['prettier-plugin-svelte'],
		useTabs: true,
		printWidth: 100,
		singleQuote: true,
		bracketSpacing: false,
		overrides: [
			{
				files: 'package.json',
				options: {
					useTabs: false,
				},
			},
		],
	},
	sideEffects: ['**/*.css'],
	files: ['dist', 'src/lib/**/*.ts', '!src/lib/**/*.test.*', '!dist/**/*.test.*'],
	exports: {
		'./package.json': './package.json',
		'./*.js': {
			types: './dist/*.d.ts',
			default: './dist/*.js',
		},
		'./*.ts': {
			types: './dist/*.d.ts',
			default: './dist/*.js',
		},
		'./*.svelte': {
			types: './dist/*.svelte.d.ts',
			svelte: './dist/*.svelte',
			default: './dist/*.svelte',
		},
	},
};

export const src_json: Src_Json = {
	name: '@ryanatkn/fuz_mastodon',
	version: '0.32.0',
	modules: [
		{
			path: 'mastodon_cache.svelte.ts',
			identifiers: [
				{
					name: 'Mastodon_Cache',
					kind: 'class',
					source_line: 6,
					members: [
						{
							name: 'load_data',
							kind: 'variable',
							modifiers: ['readonly'],
							type_signature: '() => Promise<Array<[Url, Fetch_Value_Cache_Item]> | null>',
						},
						{
							name: 'data',
							kind: 'variable',
							doc_comment: "If `undefined`, it's still loading. `null` means no data.",
							type_signature: 'Fetch_Value_Cache | undefined | null',
						},
						{
							name: 'constructor',
							kind: 'constructor',
							type_signature:
								'(load_data: () => Promise<[Url, { key: string; url: string; params: any; value: any; etag: string | null; last_modified: string | null; }][] | null>, load_on_mount?: boolean): Mastodon_Cache',
							parameters: [
								{
									name: 'load_data',
									type: '() => Promise<[Url, { key: string; url: string; params: any; value: any; etag: string | null; last_modified: string | null; }][] | null>',
									optional: false,
								},
								{
									name: 'load_on_mount',
									type: 'boolean',
									optional: false,
									default_value: 'true',
								},
							],
						},
						{
							name: 'load',
							kind: 'variable',
						},
					],
				},
				{
					name: 'mastodon_cache_context',
					kind: 'variable',
					source_line: 32,
					type_signature:
						'{ get: (error_message?: string | undefined) => Mastodon_Cache; get_maybe: () => Mastodon_Cache | undefined; set: (value: Mastodon_Cache) => Mastodon_Cache; }',
				},
			],
		},
		{
			path: 'Mastodon_Status_Item.svelte',
			identifiers: [
				{
					name: 'Mastodon_Status_Item',
					kind: 'component',
					props: [
						{
							name: 'item',
							type: 'Mastodon_Status',
							optional: false,
						},
					],
					source_line: 1,
				},
			],
			dependents: ['Mastodon_Status_Tree.svelte', 'Toot.svelte'],
		},
		{
			path: 'Mastodon_Status_Tree.svelte',
			identifiers: [
				{
					name: 'Mastodon_Status_Tree',
					kind: 'component',
					props: [
						{
							name: 'item',
							type: 'Mastodon_Status',
							optional: false,
						},
						{
							name: 'items',
							type: 'Array<Mastodon_Status>',
							optional: false,
						},
					],
					source_line: 1,
				},
			],
			dependencies: ['Mastodon_Status_Item.svelte', 'Mastodon_Status_Tree.svelte'],
			dependents: ['Mastodon_Status_Tree.svelte', 'Toot.svelte'],
		},
		{
			path: 'mastodon.ts',
			identifiers: [
				{
					name: 'to_mastodon_status_url',
					kind: 'function',
					source_line: 18,
					type_signature: '(host: string, id: string): string',
					return_type: 'string',
					parameters: [
						{
							name: 'host',
							type: 'string',
							optional: false,
						},
						{
							name: 'id',
							type: 'string',
							optional: false,
						},
					],
				},
				{
					name: 'to_mastodon_status_url_with_author',
					kind: 'function',
					source_line: 21,
					type_signature: '(host: string, id: string, author: string): string',
					return_type: 'string',
					parameters: [
						{
							name: 'host',
							type: 'string',
							optional: false,
						},
						{
							name: 'id',
							type: 'string',
							optional: false,
						},
						{
							name: 'author',
							type: 'string',
							optional: false,
						},
					],
				},
				{
					name: 'to_mastodon_status_url_with_users_author',
					kind: 'function',
					doc_comment: 'longhand for `to_mastodon_status_url_with_author`, apperas',
					source_line: 30,
					type_signature: '(host: string, id: string, author: string): string',
					return_type: 'string',
					parameters: [
						{
							name: 'host',
							type: 'string',
							optional: false,
						},
						{
							name: 'id',
							type: 'string',
							optional: false,
						},
						{
							name: 'author',
							type: 'string',
							optional: false,
						},
					],
				},
				{
					name: 'to_mastodon_api_status_url',
					kind: 'function',
					source_line: 36,
					type_signature: '(host: string, id: string): string',
					return_type: 'string',
					parameters: [
						{
							name: 'host',
							type: 'string',
							optional: false,
						},
						{
							name: 'id',
							type: 'string',
							optional: false,
						},
					],
				},
				{
					name: 'to_mastodon_api_status_context_url',
					kind: 'function',
					source_line: 39,
					type_signature: '(host: string, id: string): string',
					return_type: 'string',
					parameters: [
						{
							name: 'host',
							type: 'string',
							optional: false,
						},
						{
							name: 'id',
							type: 'string',
							optional: false,
						},
					],
				},
				{
					name: 'to_mastodon_api_favourites_url',
					kind: 'function',
					source_line: 42,
					type_signature: '(host: string, id: string): string',
					return_type: 'string',
					parameters: [
						{
							name: 'host',
							type: 'string',
							optional: false,
						},
						{
							name: 'id',
							type: 'string',
							optional: false,
						},
					],
				},
				{
					name: 'Mastodon_Status_Url',
					kind: 'type',
					source_line: 46,
					type_signature: 'Mastodon_Status_Url',
					properties: [
						{
							name: 'href',
							kind: 'variable',
							type_signature: 'string',
						},
						{
							name: 'host',
							kind: 'variable',
							type_signature: 'string',
						},
						{
							name: 'status_id',
							kind: 'variable',
							type_signature: 'string',
						},
						{
							name: 'author',
							kind: 'variable',
							type_signature: 'string',
						},
					],
				},
				{
					name: 'parse_mastodon_status_url',
					kind: 'function',
					doc_comment:
						'Parses a url to a post or API endpoint for a post, aka Mastodon status context.',
					source_line: 58,
					type_signature: '(url: string): Mastodon_Status_Url | null',
					return_type: 'Mastodon_Status_Url | null',
					return_description: 'the parsed host and id params, if any',
					parameters: [
						{
							name: 'url',
							type: 'string',
							optional: false,
						},
					],
				},
				{
					name: 'fetch_mastodon_status_context',
					kind: 'function',
					source_line: 72,
					type_signature:
						'(host: string, id: string, cache?: Map<string, { key: string; url: string; params: any; value: any; etag: string | null; last_modified: string | null; }> | null | undefined, log?: Logger | undefined, request?: RequestInit | undefined, token?: string | undefined, fetch?: ((input: RequestInfo | URL, init?: RequestInit | undefined) => Promise<...>) | undefined): Promise<...>',
					return_type: 'Promise<Mastodon_Status_Context | null>',
					parameters: [
						{
							name: 'host',
							type: 'string',
							optional: false,
						},
						{
							name: 'id',
							type: 'string',
							optional: false,
						},
						{
							name: 'cache',
							type: 'Map<string, { key: string; url: string; params: any; value: any; etag: string | null; last_modified: string | null; }> | null | undefined',
							optional: true,
						},
						{
							name: 'log',
							type: 'Logger | undefined',
							optional: true,
						},
						{
							name: 'request',
							type: 'RequestInit | undefined',
							optional: true,
						},
						{
							name: 'token',
							type: 'string | undefined',
							optional: true,
						},
						{
							name: 'fetch',
							type: '((input: RequestInfo | URL, init?: RequestInit | undefined) => Promise<Response>) | undefined',
							optional: true,
						},
					],
				},
				{
					name: 'fetch_mastodon_status',
					kind: 'function',
					source_line: 94,
					type_signature:
						'(host: string, id: string, cache?: Map<string, { key: string; url: string; params: any; value: any; etag: string | null; last_modified: string | null; }> | null | undefined, log?: Logger | undefined, request?: RequestInit | undefined, token?: string | undefined, fetch?: ((input: RequestInfo | URL, init?: RequestInit | undefined) => Promise<...>) | undefined): Promise<...>',
					return_type: 'Promise<Mastodon_Status | null>',
					parameters: [
						{
							name: 'host',
							type: 'string',
							optional: false,
						},
						{
							name: 'id',
							type: 'string',
							optional: false,
						},
						{
							name: 'cache',
							type: 'Map<string, { key: string; url: string; params: any; value: any; etag: string | null; last_modified: string | null; }> | null | undefined',
							optional: true,
						},
						{
							name: 'log',
							type: 'Logger | undefined',
							optional: true,
						},
						{
							name: 'request',
							type: 'RequestInit | undefined',
							optional: true,
						},
						{
							name: 'token',
							type: 'string | undefined',
							optional: true,
						},
						{
							name: 'fetch',
							type: '((input: RequestInfo | URL, init?: RequestInit | undefined) => Promise<Response>) | undefined',
							optional: true,
						},
					],
				},
				{
					name: 'fetch_mastodon_favourites',
					kind: 'function',
					source_line: 116,
					type_signature:
						'(host: string, status_id: string, cache?: Map<string, { key: string; url: string; params: any; value: any; etag: string | null; last_modified: string | null; }> | null | undefined, log?: Logger | undefined, request?: RequestInit | undefined, token?: string | undefined, fetch?: ((input: RequestInfo | URL, init?: RequestInit | undefined) => Promise<...>) | undefined): Promise<...>',
					return_type: 'Promise<Mastodon_Favourite[] | null>',
					parameters: [
						{
							name: 'host',
							type: 'string',
							optional: false,
						},
						{
							name: 'status_id',
							type: 'string',
							optional: false,
						},
						{
							name: 'cache',
							type: 'Map<string, { key: string; url: string; params: any; value: any; etag: string | null; last_modified: string | null; }> | null | undefined',
							optional: true,
						},
						{
							name: 'log',
							type: 'Logger | undefined',
							optional: true,
						},
						{
							name: 'request',
							type: 'RequestInit | undefined',
							optional: true,
						},
						{
							name: 'token',
							type: 'string | undefined',
							optional: true,
						},
						{
							name: 'fetch',
							type: '((input: RequestInfo | URL, init?: RequestInit | undefined) => Promise<Response>) | undefined',
							optional: true,
						},
					],
				},
				{
					name: 'Mastodon_Status_Context',
					kind: 'type',
					doc_comment: 'Result from `https://:host/api/v1/statuses/:id/context`.',
					see_also: ['https://docs.joinmastodon.org/entities/Context/'],
					source_line: 144,
					type_signature: 'Mastodon_Status_Context',
					properties: [
						{
							name: 'ancestors',
							kind: 'variable',
							type_signature: 'Array<Mastodon_Status>',
						},
						{
							name: 'descendants',
							kind: 'variable',
							type_signature: 'Array<Mastodon_Status>',
						},
					],
				},
				{
					name: 'Mastodon_Status',
					kind: 'type',
					source_line: 149,
					type_signature: 'Mastodon_Status',
					properties: [
						{
							name: 'id',
							kind: 'variable',
							type_signature: 'string',
						},
						{
							name: 'created_at',
							kind: 'variable',
							type_signature: 'string',
						},
						{
							name: 'in_reply_to_id',
							kind: 'variable',
							type_signature: 'string',
						},
						{
							name: 'in_reply_to_account_id',
							kind: 'variable',
							type_signature: 'string',
						},
						{
							name: 'sensitive',
							kind: 'variable',
							type_signature: 'boolean',
						},
						{
							name: 'spoiler_text',
							kind: 'variable',
							type_signature: 'string',
						},
						{
							name: 'visibility',
							kind: 'variable',
							type_signature: 'string',
						},
						{
							name: 'language',
							kind: 'variable',
							type_signature: 'string',
						},
						{
							name: 'uri',
							kind: 'variable',
							type_signature: 'string',
						},
						{
							name: 'url',
							kind: 'variable',
							type_signature: 'string',
						},
						{
							name: 'replies_count',
							kind: 'variable',
							type_signature: 'number',
						},
						{
							name: 'reblogs_count',
							kind: 'variable',
							type_signature: 'number',
						},
						{
							name: 'favourites_count',
							kind: 'variable',
							type_signature: 'number',
						},
						{
							name: 'edited_at',
							kind: 'variable',
							type_signature: 'null | string',
						},
						{
							name: 'favourited',
							kind: 'variable',
							type_signature: 'boolean',
						},
						{
							name: 'reblogged',
							kind: 'variable',
							type_signature: 'boolean',
						},
						{
							name: 'muted',
							kind: 'variable',
							type_signature: 'boolean',
						},
						{
							name: 'bookmarked',
							kind: 'variable',
							type_signature: 'boolean',
						},
						{
							name: 'content',
							kind: 'variable',
							type_signature: 'string',
						},
						{
							name: 'filtered',
							kind: 'variable',
							type_signature: 'Array<unknown>',
						},
						{
							name: 'reblog',
							kind: 'variable',
							type_signature: 'unknown',
						},
						{
							name: 'account',
							kind: 'variable',
							type_signature:
								'{\n\t\tid: string;\n\t\tusername: string;\n\t\tacct: string;\n\t\tdisplay_name: string;\n\t\tlocked: boolean;\n\t\tbot: boolean;\n\t\tdiscoverable: boolean;\n\t\tgroup: boolean;\n\t\tcreated_at: string;\n\t\tnote: string;\n\t\turl: string;\n\t\tavatar: string;\n\t\tavatar_static: string;\n\t\theader: string;\n\t\theader_static: string;\n\t\tfollowers_count: number;\n\t\tfollowing_count: number;\n\t\tstatuses_count: number;\n\t\tlast_status_at: string;\n\t\temojis: Array<unknown>;\n\t\tfields: Array<unknown>;\n\t}',
						},
						{
							name: 'media_attachments',
							kind: 'variable',
							type_signature: 'Array<unknown>',
						},
						{
							name: 'mentions',
							kind: 'variable',
							type_signature:
								'[\n\t\t{\n\t\t\tid: string;\n\t\t\tusername: string;\n\t\t\turl: string;\n\t\t\tacct: string;\n\t\t},\n\t]',
						},
						{
							name: 'tags',
							kind: 'variable',
							type_signature: '[\n\t\t{\n\t\t\tname: string;\n\t\t\turl: string;\n\t\t},\n\t]',
						},
						{
							name: 'emojis',
							kind: 'variable',
							type_signature: 'Array<unknown>',
						},
						{
							name: 'card',
							kind: 'variable',
							type_signature: 'unknown',
						},
						{
							name: 'poll',
							kind: 'variable',
							type_signature: 'unknown',
						},
					],
				},
				{
					name: 'Mastodon_Favourite',
					kind: 'type',
					source_line: 214,
					type_signature: 'Mastodon_Favourite',
					properties: [
						{
							name: 'id',
							kind: 'variable',
							type_signature: 'string',
						},
						{
							name: 'username',
							kind: 'variable',
							type_signature: 'string',
						},
						{
							name: 'acct',
							kind: 'variable',
							type_signature: 'string',
						},
						{
							name: 'display_name',
							kind: 'variable',
							type_signature: 'string',
						},
						{
							name: 'locked',
							kind: 'variable',
							type_signature: 'boolean',
						},
						{
							name: 'bot',
							kind: 'variable',
							type_signature: 'boolean',
						},
						{
							name: 'discoverable',
							kind: 'variable',
							type_signature: 'boolean',
						},
						{
							name: 'group',
							kind: 'variable',
							type_signature: 'boolean',
						},
						{
							name: 'created_at',
							kind: 'variable',
							type_signature: 'string',
						},
						{
							name: 'note',
							kind: 'variable',
							type_signature: 'string',
						},
						{
							name: 'url',
							kind: 'variable',
							type_signature: 'string',
						},
						{
							name: 'avatar',
							kind: 'variable',
							type_signature: 'string',
						},
						{
							name: 'avatar_static',
							kind: 'variable',
							type_signature: 'string',
						},
						{
							name: 'header',
							kind: 'variable',
							type_signature: 'string',
						},
						{
							name: 'header_static',
							kind: 'variable',
							type_signature: 'string',
						},
						{
							name: 'followers_count',
							kind: 'variable',
							type_signature: 'number',
						},
						{
							name: 'following_count',
							kind: 'variable',
							type_signature: 'number',
						},
						{
							name: 'statuses_count',
							kind: 'variable',
							type_signature: 'number',
						},
						{
							name: 'last_status_at',
							kind: 'variable',
							type_signature: 'string',
						},
						{
							name: 'emojis',
							kind: 'variable',
							type_signature: 'Array<unknown>',
						},
						{
							name: 'fields',
							kind: 'variable',
							type_signature:
								'Array<{\n\t\tname: string;\n\t\tvalue: string;\n\t\tverified_at: string; // Datetime\n\t}>',
						},
					],
				},
				{
					name: 'Reply_Filter',
					kind: 'type',
					doc_comment:
						'When filtering replies, at least one rule must pass for a reply to be included.',
					source_line: 245,
					type_signature: 'Reply_Filter',
				},
				{
					name: 'Favourited_By_Reply_Filter',
					kind: 'type',
					source_line: 250,
					type_signature: 'Favourited_By_Reply_Filter',
					properties: [
						{
							name: 'type',
							kind: 'variable',
							type_signature: "'favourited_by'",
						},
						{
							name: 'favourited_by',
							kind: 'variable',
							type_signature: 'Array<string>',
						},
					],
				},
				{
					name: 'Minimum_Favourites_Reply_Filter',
					kind: 'type',
					source_line: 255,
					type_signature: 'Minimum_Favourites_Reply_Filter',
					properties: [
						{
							name: 'type',
							kind: 'variable',
							type_signature: "'minimum_favourites'",
						},
						{
							name: 'minimum_favourites',
							kind: 'variable',
							type_signature: 'number',
						},
					],
				},
				{
					name: 'Custom_Reply_Filter',
					kind: 'type',
					source_line: 260,
					type_signature: 'Custom_Reply_Filter',
					properties: [
						{
							name: 'type',
							kind: 'variable',
							type_signature: "'custom'",
						},
						{
							name: 'should_include',
							kind: 'variable',
							type_signature:
								'(\n\t\tstatus: Mastodon_Status,\n\t\troot_status: Mastodon_Status,\n\t\tstatus_context: Mastodon_Status_Context,\n\t) => boolean',
						},
					],
				},
				{
					name: 'Create_Reply_Filters',
					kind: 'type',
					source_line: 269,
					type_signature: 'Create_Reply_Filters',
				},
				{
					name: 'filter_valid_replies',
					kind: 'function',
					source_line: 276,
					type_signature:
						'(root_status: Mastodon_Status, status_context: Mastodon_Status_Context, reply_filter: Reply_Filter | Reply_Filter[] | null, cache: Map<...> | ... 1 more ... | undefined, log: Logger | undefined): Promise<...>',
					return_type: 'Promise<Mastodon_Status[]>',
					parameters: [
						{
							name: 'root_status',
							type: 'Mastodon_Status',
							optional: false,
						},
						{
							name: 'status_context',
							type: 'Mastodon_Status_Context',
							optional: false,
						},
						{
							name: 'reply_filter',
							type: 'Reply_Filter | Reply_Filter[] | null',
							optional: false,
						},
						{
							name: 'cache',
							type: 'Map<string, { key: string; url: string; params: any; value: any; etag: string | null; last_modified: string | null; }> | null | undefined',
							optional: false,
						},
						{
							name: 'log',
							type: 'Logger | undefined',
							optional: false,
						},
					],
				},
			],
			dependents: ['Toot.svelte', 'Toot_Input.svelte', 'Toot_Loader.svelte'],
		},
		{
			path: 'storage.ts',
			identifiers: [
				{
					name: 'load_from_storage',
					kind: 'function',
					doc_comment:
						'Loads `key` and falls back to `defaultValue`.\nIf `validate` is provided and throws, it removes the `key` and returns `undefined`.',
					source_line: 13,
					type_signature:
						'<T>(key: string, to_default_value: () => T, validate?: ((value: any) => asserts value is T) | undefined): T',
					return_type: 'T',
					parameters: [
						{
							name: 'key',
							type: 'string',
							optional: false,
						},
						{
							name: 'to_default_value',
							type: '() => T',
							optional: false,
						},
						{
							name: 'validate',
							type: '((value: any) => asserts value is T) | undefined',
							optional: true,
						},
					],
				},
				{
					name: 'set_in_storage',
					kind: 'function',
					doc_comment:
						'Sets `value` at `key`.\nImportantly, if `value` is `undefined` the `key` is removed,\nbut a `value` of `null` is stored.',
					source_line: 40,
					type_signature: '(key: string, value: any): void',
					return_type: 'void',
					parameters: [
						{
							name: 'key',
							type: 'string',
							optional: false,
						},
						{
							name: 'value',
							type: 'any',
							optional: false,
						},
					],
				},
			],
			dependents: ['Toot.svelte'],
		},
		{
			path: 'Toot_Input.svelte',
			identifiers: [
				{
					name: 'Toot_Input',
					kind: 'component',
					props: [
						{
							name: 'url',
							type: 'string',
							optional: false,
							bindable: true,
						},
						{
							name: 'attrs',
							type: "SvelteHTMLElements['input'] | undefined",
							optional: true,
						},
					],
					source_line: 1,
				},
			],
			dependencies: ['mastodon.ts'],
			dependents: ['Toot.svelte'],
		},
		{
			path: 'Toot_Loader.svelte',
			identifiers: [
				{
					name: 'Toot_Loader',
					kind: 'component',
					props: [
						{
							name: 'host',
							type: 'string | null',
							optional: false,
							description: "The host part of the url, like `'mastodon.ryanatkn.com'`.",
						},
						{
							name: 'id',
							type: 'string | null',
							optional: false,
							description: "The status id to fetch, like `'110702983310017651'`.",
						},
						{
							name: 'include_ancestors',
							type: 'boolean',
							optional: true,
							description: 'Whether to fetch and display the ancestors in the status context.',
						},
						{
							name: 'include_replies',
							type: 'boolean',
							optional: true,
							description:
								'Whether to fetch and display replies aka descendants in the status context.',
						},
						{
							name: 'cache',
							type: 'Fetch_Value_Cache | null | undefined',
							optional: true,
							description: 'Optional API result cache.',
						},
						{
							name: 'log',
							type: 'Logger | undefined',
							optional: true,
							description: 'Optional logger for network calls.',
						},
						{
							name: 'loading',
							type: 'boolean | undefined',
							optional: true,
							bindable: true,
						},
						{
							name: 'item',
							type: 'Mastodon_Status | null | undefined',
							optional: true,
							bindable: true,
						},
						{
							name: 'status_context',
							type: 'Mastodon_Status_Context | null | undefined',
							optional: true,
							bindable: true,
						},
						{
							name: 'replies',
							type: 'Array<Mastodon_Status> | null | undefined',
							optional: true,
							bindable: true,
						},
						{
							name: 'reply_filter',
							type: 'Reply_Filter | Array<Reply_Filter> | Create_Reply_Filters | null',
							optional: true,
							description:
								'Get a list of rules that controls whether replies are shown or not.\nIf omitted, all replies are included.',
						},
						{
							name: 'load_time',
							type: 'number | undefined',
							optional: true,
							bindable: true,
						},
						{
							name: 'children',
							type: 'Snippet<\n\t\t\t[\n\t\t\t\t{\n\t\t\t\t\t/**\n\t\t\t\t\t * `null` here is a failed loading condition.\n\t\t\t\t\t */\n\t\t\t\t\titem: Mastodon_Status | null | undefined;\n\t\t\t\t\t/**\n\t\t\t\t\t * `null` here is a failed loading condition.\n\t\t\t\t\t */\n\t\t\t\t\tstatus_context: Mastodon_Status_Context | null | undefined;\n\t\t\t\t\t/**\n\t\t\t\t\t * `null` here is a failed loading condition for `item` or `status_context`.\n\t\t\t\t\t */\n\t\t\t\t\treplies: Array<Mastodon_Status> | null | undefined;\n\t\t\t\t\tload: () => Promise<void>;\n\t\t\t\t\tloading: boolean | undefined;\n\t\t\t\t\tload_time: number | undefined;\n\t\t\t\t},\n\t\t\t]\n\t\t>',
							optional: false,
						},
					],
					source_line: 1,
				},
			],
			dependencies: ['mastodon.ts'],
			dependents: ['Toot.svelte'],
		},
		{
			path: 'Toot.svelte',
			identifiers: [
				{
					name: 'Toot',
					kind: 'component',
					props: [
						{
							name: 'url',
							type: 'string',
							optional: false,
						},
						{
							name: 'updated_url',
							type: 'string',
							optional: true,
							description: 'Defaults to the `url`, but can be updated by user input.',
							bindable: true,
						},
						{
							name: 'include_ancestors',
							type: 'boolean',
							optional: true,
							description: 'Whether to fetch and display the ancestors in the status context.',
						},
						{
							name: 'include_replies',
							type: 'boolean',
							optional: true,
							description:
								'Whether to fetch and display replies aka descendants in the status context.',
						},
						{
							name: 'reply_filter',
							type: 'Reply_Filter | Array<Reply_Filter> | Create_Reply_Filters | null',
							optional: true,
							description: 'Get a list of rules that controls whether replies are shown or not.',
						},
						{
							name: 'cache',
							type: 'Fetch_Value_Cache | null | undefined',
							optional: true,
							description:
								'Optional API result cache.\nSee `Mastodon_Cache` and `get_mastodon_cache`/`set_mastodon_cache`.',
						},
						{
							name: 'log',
							type: 'Logger | undefined',
							optional: true,
							description: 'Optional logger for network calls.',
						},
						{
							name: 'loading',
							type: 'boolean | undefined',
							optional: true,
							description: '',
							bindable: true,
						},
						{
							name: 'load_time',
							type: 'number | undefined',
							optional: true,
							description: '',
							bindable: true,
						},
						{
							name: 'settings_storage_key',
							type: 'string | undefined',
							optional: true,
						},
						{
							name: 'initial_show_settings',
							type: 'boolean',
							optional: true,
						},
						{
							name: 'show_settings',
							type: 'boolean',
							optional: true,
							bindable: true,
						},
						{
							name: 'autoload_storage_key',
							type: 'string | undefined',
							optional: true,
						},
						{
							name: 'initial_autoload',
							type: 'boolean',
							optional: true,
						},
						{
							name: 'autoload',
							type: 'boolean',
							optional: true,
						},
						{
							name: 'onreset',
							type: '() => void',
							optional: true,
						},
						{
							name: 'settings',
							type: 'Snippet',
							optional: true,
						},
					],
					source_line: 1,
				},
			],
			dependencies: [
				'Mastodon_Status_Item.svelte',
				'Mastodon_Status_Tree.svelte',
				'Toot_Input.svelte',
				'Toot_Loader.svelte',
				'mastodon.ts',
				'storage.ts',
			],
		},
	],
};
